# Generated by Django 6.0 on 2025-12-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("lead_count", "Lead Count"),
                            ("conversion_rate", "Conversion Rate"),
                            ("revenue", "Revenue"),
                            ("service_requests", "Service Requests"),
                            ("avg_deal_size", "Average Deal Size"),
                            ("lead_source_performance", "Lead Source Performance"),
                            ("priority_distribution", "Priority Distribution"),
                            ("response_time", "Response Time"),
                        ],
                        help_text="Type of metric",
                        max_length=50,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("all_time", "All Time"),
                        ],
                        help_text="Time period for this metric",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField(help_text="Start of the period")),
                ("period_end", models.DateTimeField(help_text="End of the period")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Primary metric value",
                        max_digits=15,
                    ),
                ),
                (
                    "secondary_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Secondary metric value (for ratios, percentages, etc.)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metric data and breakdowns"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Analytics Metric",
                "verbose_name_plural": "Analytics Metrics",
                "db_table": "analytics_metrics",
                "ordering": ["-period_start", "metric_type"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "period_type"],
                        name="analytics_m_metric__a0905f_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="analytics_m_period__4821ca_idx",
                    ),
                    models.Index(
                        fields=["calculated_at"], name="analytics_m_calcula_bedba2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("metric_type", "period_type", "period_start"),
                        name="unique_metric_period",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversionFunnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("visitor", "Website Visitor"),
                            ("lead", "Lead Generated"),
                            ("qualified", "Qualified Lead"),
                            ("proposal", "Proposal Sent"),
                            ("negotiation", "In Negotiation"),
                            ("customer", "Converted Customer"),
                        ],
                        help_text="Funnel stage",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField(help_text="Start of the period")),
                ("period_end", models.DateTimeField(help_text="End of the period")),
                (
                    "count",
                    models.IntegerField(
                        default=0, help_text="Number of records in this stage"
                    ),
                ),
                (
                    "converted_count",
                    models.IntegerField(
                        default=0, help_text="Number that converted to next stage"
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Conversion rate to next stage (%)",
                        max_digits=5,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conversion Funnel",
                "verbose_name_plural": "Conversion Funnel",
                "db_table": "conversion_funnel",
                "ordering": ["period_start", "stage"],
                "indexes": [
                    models.Index(
                        fields=["stage", "period_start"],
                        name="conversion__stage_999072_idx",
                    ),
                    models.Index(
                        fields=["calculated_at"], name="conversion__calcula_a526b7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("lead_velocity", "Lead Velocity"),
                            ("conversion_velocity", "Conversion Velocity"),
                            ("customer_acquisition_cost", "Customer Acquisition Cost"),
                            ("customer_lifetime_value", "Customer Lifetime Value"),
                            ("service_efficiency", "Service Efficiency"),
                            ("revenue_growth", "Revenue Growth"),
                            ("market_penetration", "Market Penetration"),
                        ],
                        help_text="Type of KPI",
                        max_length=50,
                    ),
                ),
                ("period_start", models.DateTimeField(help_text="Start of the period")),
                ("period_end", models.DateTimeField(help_text="End of the period")),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2, help_text="Current KPI value", max_digits=15
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous period KPI value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target KPI value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "change_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage change from previous period",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "target_achievement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target achievement percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict, help_text="Additional context and breakdown data"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Performance Indicator",
                "verbose_name_plural": "Performance Indicators",
                "db_table": "performance_indicators",
                "ordering": ["-period_start", "kpi_type"],
                "indexes": [
                    models.Index(
                        fields=["kpi_type", "period_start"],
                        name="performance_kpi_typ_db0aeb_idx",
                    ),
                    models.Index(
                        fields=["calculated_at"], name="performance_calcula_8d698d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RevenueTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revenue_type",
                    models.CharField(
                        choices=[
                            ("actual", "Actual Revenue"),
                            ("projected", "Projected Revenue"),
                            ("pipeline", "Pipeline Value"),
                        ],
                        help_text="Type of revenue tracking",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField(help_text="Start of the period")),
                ("period_end", models.DateTimeField(help_text="End of the period")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Revenue amount", max_digits=15
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Revenue breakdown by source, product, etc.",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Revenue Tracking",
                "verbose_name_plural": "Revenue Tracking",
                "db_table": "revenue_tracking",
                "ordering": ["-period_start", "revenue_type"],
                "indexes": [
                    models.Index(
                        fields=["revenue_type", "period_start"],
                        name="revenue_tra_revenue_ee23a1_idx",
                    ),
                    models.Index(
                        fields=["calculated_at"], name="revenue_tra_calcula_e6b4de_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceWorkload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateTimeField(help_text="Start of the period")),
                ("period_end", models.DateTimeField(help_text="End of the period")),
                (
                    "total_requests",
                    models.IntegerField(default=0, help_text="Total service requests"),
                ),
                (
                    "open_requests",
                    models.IntegerField(default=0, help_text="Open service requests"),
                ),
                (
                    "closed_requests",
                    models.IntegerField(default=0, help_text="Closed service requests"),
                ),
                (
                    "overdue_requests",
                    models.IntegerField(
                        default=0, help_text="Overdue service requests"
                    ),
                ),
                (
                    "avg_response_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average response time in hours",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "avg_resolution_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average resolution time in hours",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "satisfaction_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average satisfaction score (1-5)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Workload breakdown by various dimensions",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service Workload",
                "verbose_name_plural": "Service Workload",
                "db_table": "service_workload",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="service_wor_period__8ce7e9_idx",
                    ),
                    models.Index(
                        fields=["calculated_at"], name="service_wor_calcula_5fd06e_idx"
                    ),
                ],
            },
        ),
    ]
