# Generated by Django 4.2.7 on 2025-12-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('daily', 'Daily Trends'), ('weekly', 'Weekly Trends'), ('monthly', 'Monthly Trends'), ('seasonal', 'Seasonal Trends')], help_text='Type of trend analysis', max_length=20)),
                ('period_start', models.DateTimeField(help_text='Start of the analysis period')),
                ('period_end', models.DateTimeField(help_text='End of the analysis period')),
                ('trend_data', models.JSONField(default=dict, help_text='Detailed trend analysis data')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount in the trend period', max_digits=15)),
                ('average_amount', models.DecimalField(decimal_places=2, default=0, help_text='Average amount per period unit', max_digits=15)),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Growth rate compared to previous period', max_digits=10, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Trend Analysis',
                'verbose_name_plural': 'Payment Trend Analysis',
                'db_table': 'payment_trend_analysis',
                'ordering': ['-period_start', 'trend_type'],
                'indexes': [models.Index(fields=['trend_type', 'period_start'], name='payment_tre_trend_t_e45d1f_idx'), models.Index(fields=['calculated_at'], name='payment_tre_calcula_8af809_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_type', models.CharField(choices=[('cash_flow', 'Cash Flow Analysis'), ('payment_trends', 'Payment Trends'), ('collection_efficiency', 'Collection Efficiency'), ('revenue_forecast', 'Revenue Forecast'), ('outstanding_analysis', 'Outstanding Analysis'), ('payment_method_analysis', 'Payment Method Analysis')], help_text='Type of financial analytics', max_length=50)),
                ('period_start', models.DateTimeField(help_text='Start of the analysis period')),
                ('period_end', models.DateTimeField(help_text='End of the analysis period')),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, help_text='Total amount invoiced', max_digits=15)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, help_text='Total amount collected', max_digits=15)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, help_text='Total outstanding amount', max_digits=15)),
                ('collection_rate', models.DecimalField(decimal_places=2, default=0, help_text='Collection rate percentage', max_digits=5)),
                ('average_payment_time', models.DecimalField(blank=True, decimal_places=2, help_text='Average payment time in days', max_digits=10, null=True)),
                ('analytics_data', models.JSONField(default=dict, help_text='Detailed analytics breakdown and trends')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Analytics',
                'verbose_name_plural': 'Financial Analytics',
                'db_table': 'financial_analytics',
                'ordering': ['-period_start', 'analytics_type'],
                'indexes': [models.Index(fields=['analytics_type', 'period_start'], name='financial_a_analyti_6b7721_idx'), models.Index(fields=['period_start', 'period_end'], name='financial_a_period__f9f5e9_idx'), models.Index(fields=['calculated_at'], name='financial_a_calcula_e322e7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='financialanalytics',
            constraint=models.UniqueConstraint(fields=('analytics_type', 'period_start', 'period_end'), name='unique_financial_analytics_period'),
        ),
    ]
