# Generated by Django 4.2.7 on 2025-12-31 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='Unique contract number', max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='Contract start date')),
                ('end_date', models.DateField(help_text='Contract end date')),
                ('annual_value', models.DecimalField(decimal_places=2, help_text='Annual contract value', max_digits=10)),
                ('maintenance_frequency', models.CharField(default='quarterly', help_text='Maintenance frequency (monthly, quarterly, bi-annual, annual)', max_length=50)),
                ('services_included', models.JSONField(default=list, help_text='List of services included in the contract')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('renewal_pending', 'Renewal Pending')], default='active', help_text='Current contract status', max_length=20)),
                ('renewal_reminder_sent', models.BooleanField(default=False, help_text='Whether renewal reminder has been sent')),
                ('auto_renewal', models.BooleanField(default=False, help_text='Whether contract auto-renews')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Contract terms and conditions')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this contract')),
            ],
            options={
                'verbose_name': 'AMC Contract',
                'verbose_name_plural': 'AMC Contracts',
                'db_table': 'amc_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(help_text='Unique project number', max_length=20, unique=True)),
                ('system_capacity', models.DecimalField(decimal_places=2, help_text='System capacity in kW', max_digits=10)),
                ('panel_brand', models.CharField(help_text='Solar panel brand', max_length=100)),
                ('panel_model', models.CharField(blank=True, help_text='Solar panel model', max_length=100)),
                ('panel_quantity', models.IntegerField(help_text='Number of solar panels')),
                ('inverter_brand', models.CharField(help_text='Inverter brand', max_length=100)),
                ('inverter_model', models.CharField(blank=True, help_text='Inverter model', max_length=100)),
                ('inverter_quantity', models.IntegerField(default=1, help_text='Number of inverters')),
                ('installation_type', models.CharField(choices=[('rooftop', 'Rooftop'), ('ground_mount', 'Ground Mount'), ('carport', 'Carport'), ('floating', 'Floating Solar'), ('agri_solar', 'Agri Solar')], default='rooftop', help_text='Type of installation', max_length=50)),
                ('status', models.CharField(choices=[('quotation', 'Quotation'), ('approved', 'Approved'), ('design', 'Design Phase'), ('permits', 'Permits & Approvals'), ('procurement', 'Procurement'), ('installation', 'Installation'), ('testing', 'Testing & Commissioning'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='quotation', help_text='Current project status', max_length=30)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Project completion percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('project_value', models.DecimalField(decimal_places=2, help_text='Total project value', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by customer', max_digits=12)),
                ('quotation_date', models.DateField(blank=True, help_text='Date when quotation was provided', null=True)),
                ('approval_date', models.DateField(blank=True, help_text='Date when project was approved by customer', null=True)),
                ('installation_start_date', models.DateField(blank=True, help_text='Installation start date', null=True)),
                ('installation_end_date', models.DateField(blank=True, help_text='Installation completion date', null=True)),
                ('commissioning_date', models.DateField(blank=True, help_text='System commissioning date', null=True)),
                ('completion_date', models.DateField(blank=True, help_text='Project completion date', null=True)),
                ('installation_address', models.TextField(blank=True, help_text='Installation site address (if different from customer address)')),
                ('estimated_annual_generation', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated annual energy generation in kWh', max_digits=10, null=True)),
                ('warranty_years', models.IntegerField(default=25, help_text='Warranty period in years')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Project notes and comments')),
            ],
            options={
                'verbose_name': 'Installation Project',
                'verbose_name_plural': 'Installation Projects',
                'db_table': 'installation_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Unique ticket number', max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('warranty', 'Warranty Claim'), ('technical_support', 'Technical Support'), ('installation_issue', 'Installation Issue'), ('performance_issue', 'Performance Issue'), ('other', 'Other')], help_text='Type of service request', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the request', max_length=20)),
                ('subject', models.CharField(help_text='Subject or title of the request', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue or request')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_customer', 'Pending Customer Response'), ('pending_parts', 'Pending Parts'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', help_text='Current status of the request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Date when request was resolved', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Date when request was closed', null=True)),
                ('source_email', models.TextField(blank=True, help_text='Original email content if created from email')),
                ('source_data', models.JSONField(default=dict, help_text='Additional source data (chatbot, form, etc.)')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the request was resolved')),
                ('customer_satisfaction', models.IntegerField(blank=True, help_text='Customer satisfaction rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
