# Generated by Django 4.2.7 on 2025-12-31 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to handle this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(help_text='Customer who raised this request', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='installation_project',
            field=models.ForeignKey(blank=True, help_text='Related installation project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='services.installationproject'),
        ),
        migrations.AddField(
            model_name='installationproject',
            name='customer',
            field=models.ForeignKey(help_text='Customer for this project', on_delete=django.db.models.deletion.CASCADE, related_name='installation_projects', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='installationproject',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='Project manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installationproject',
            name='sales_person',
            field=models.ForeignKey(blank=True, help_text='Sales person who closed this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='Person responsible for this contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_amc_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='customer',
            field=models.ForeignKey(help_text='Customer for this AMC contract', on_delete=django.db.models.deletion.CASCADE, related_name='amc_contracts', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='installation_project',
            field=models.ForeignKey(help_text='Related installation project', on_delete=django.db.models.deletion.CASCADE, related_name='amc_contracts', to='services.installationproject'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['ticket_number'], name='service_req_ticket__8da7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['customer', 'status'], name='service_req_custome_7d484f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status'], name='service_req_status_ba17eb_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['priority'], name='service_req_priorit_c7edb9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['assigned_to'], name='service_req_assigne_a3c572_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['created_at'], name='service_req_created_bc6133_idx'),
        ),
        migrations.AddIndex(
            model_name='installationproject',
            index=models.Index(fields=['project_number'], name='installatio_project_cb8bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='installationproject',
            index=models.Index(fields=['customer', 'status'], name='installatio_custome_40d224_idx'),
        ),
        migrations.AddIndex(
            model_name='installationproject',
            index=models.Index(fields=['status'], name='installatio_status_b4cf62_idx'),
        ),
        migrations.AddIndex(
            model_name='installationproject',
            index=models.Index(fields=['project_manager'], name='installatio_project_4976be_idx'),
        ),
        migrations.AddIndex(
            model_name='installationproject',
            index=models.Index(fields=['created_at'], name='installatio_created_d549ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='installationproject',
            constraint=models.CheckConstraint(check=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='valid_progress_percentage'),
        ),
        migrations.AddConstraint(
            model_name='installationproject',
            constraint=models.CheckConstraint(check=models.Q(('project_value__gte', 0)), name='valid_project_value'),
        ),
        migrations.AddConstraint(
            model_name='installationproject',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__gte', 0)), name='valid_amount_paid'),
        ),
        migrations.AddIndex(
            model_name='amccontract',
            index=models.Index(fields=['contract_number'], name='amc_contrac_contrac_478168_idx'),
        ),
        migrations.AddIndex(
            model_name='amccontract',
            index=models.Index(fields=['customer', 'status'], name='amc_contrac_custome_b2edee_idx'),
        ),
        migrations.AddIndex(
            model_name='amccontract',
            index=models.Index(fields=['status'], name='amc_contrac_status_9edb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='amccontract',
            index=models.Index(fields=['end_date'], name='amc_contrac_end_dat_127b46_idx'),
        ),
        migrations.AddIndex(
            model_name='amccontract',
            index=models.Index(fields=['created_at'], name='amc_contrac_created_dac6fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='amccontract',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='valid_contract_dates'),
        ),
        migrations.AddConstraint(
            model_name='amccontract',
            constraint=models.CheckConstraint(check=models.Q(('annual_value__gte', 0)), name='valid_annual_value'),
        ),
    ]
