# Generated by Django 4.2.7 on 2025-12-31 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_servicerequeststatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCRenewalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('30_days', '30 Days Before Expiry'), ('15_days', '15 Days Before Expiry'), ('7_days', '7 Days Before Expiry'), ('expired', 'Contract Expired')], max_length=20)),
                ('alert_date', models.DateField(help_text='Date when alert should be triggered')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.JSONField(default=list, help_text='List of email addresses alert was sent to')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('amc_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_alerts', to='services.amccontract')),
            ],
            options={
                'verbose_name': 'AMC Renewal Alert',
                'verbose_name_plural': 'AMC Renewal Alerts',
                'db_table': 'amc_renewal_alerts',
                'ordering': ['-alert_date'],
                'indexes': [models.Index(fields=['alert_date', 'status'], name='amc_renewal_alert_d_9a7a1e_idx'), models.Index(fields=['amc_contract', 'alert_type'], name='amc_renewal_amc_con_8fdbfe_idx')],
                'unique_together': {('amc_contract', 'alert_type')},
            },
        ),
    ]
