# Generated by Django 4.2.7 on 2025-12-31 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_amcrenewalalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('installation_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.installationproject')),
            ],
            options={
                'verbose_name': 'Project Status History',
                'verbose_name_plural': 'Project Status Histories',
                'db_table': 'project_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('status_change', 'Status Change'), ('milestone_completed', 'Milestone Completed'), ('milestone_overdue', 'Milestone Overdue'), ('project_overdue', 'Project Overdue'), ('payment_due', 'Payment Due'), ('custom', 'Custom Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to notify')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional notification data')),
                ('installation_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.installationproject')),
            ],
            options={
                'verbose_name': 'Project Notification',
                'verbose_name_plural': 'Project Notifications',
                'db_table': 'project_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['installation_project', 'status'], name='project_not_install_27a98d_idx'), models.Index(fields=['notification_type'], name='project_not_notific_78cb81_idx'), models.Index(fields=['created_at'], name='project_not_created_58830e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('quotation', 'Quotation'), ('approval', 'Customer Approval'), ('design', 'Design Completion'), ('permits', 'Permits Obtained'), ('procurement', 'Equipment Procurement'), ('installation_start', 'Installation Start'), ('installation_complete', 'Installation Complete'), ('testing', 'Testing & Commissioning'), ('handover', 'Project Handover'), ('custom', 'Custom Milestone')], max_length=30)),
                ('name', models.CharField(help_text='Milestone name or description', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateField(blank=True, help_text='Planned completion date', null=True)),
                ('actual_date', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Person responsible for this milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('installation_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='services.installationproject')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'db_table': 'project_milestones',
                'ordering': ['planned_date', 'created_at'],
                'indexes': [models.Index(fields=['installation_project', 'status'], name='project_mil_install_bbf2b7_idx'), models.Index(fields=['planned_date'], name='project_mil_planned_5a5965_idx'), models.Index(fields=['assigned_to'], name='project_mil_assigne_f088b7_idx')],
            },
        ),
    ]
