# Generated by Django 4.2.7 on 2025-12-31 12:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_projectstatushistory_projectnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=20, unique=True)),
                ('invoice_type', models.CharField(choices=[('project', 'Project Invoice'), ('amc', 'AMC Invoice'), ('service', 'Service Invoice'), ('maintenance', 'Maintenance Invoice'), ('other', 'Other')], help_text='Type of invoice', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Invoice subtotal before taxes', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Tax rate percentage (GST/VAT)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Tax amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount including tax', max_digits=12)),
                ('invoice_date', models.DateField(help_text='Invoice date')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', help_text='Invoice status', max_length=20)),
                ('line_items', models.JSONField(default=list, help_text='Invoice line items with description, quantity, rate, amount')),
                ('notes', models.TextField(blank=True, help_text='Invoice notes or terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Date when invoice was sent to customer', null=True)),
                ('amc_contract', models.ForeignKey(blank=True, help_text='Related AMC contract', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='services.amccontract')),
                ('customer', models.ForeignKey(help_text='Customer for this invoice', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customer')),
                ('installation_project', models.ForeignKey(blank=True, help_text='Related installation project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='services.installationproject')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('advance', 'Advance Payment'), ('material_delivery', 'Material Delivery'), ('installation_start', 'Installation Start'), ('installation_complete', 'Installation Complete'), ('commissioning', 'Commissioning'), ('final_payment', 'Final Payment'), ('custom', 'Custom Milestone')], help_text='Type of payment milestone', max_length=30)),
                ('name', models.CharField(help_text='Milestone name or description', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the milestone')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Milestone payment amount', max_digits=12)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of total project value', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', help_text='Payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this milestone')),
                ('installation_project', models.ForeignKey(help_text='Related installation project', on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='services.installationproject')),
            ],
            options={
                'verbose_name': 'Payment Milestone',
                'verbose_name_plural': 'Payment Milestones',
                'db_table': 'payment_milestones',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(help_text='Unique payment reference number', max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('online', 'Online Payment'), ('other', 'Other')], help_text='Payment method used', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Bank/Gateway transaction ID', max_length=100)),
                ('cheque_number', models.CharField(blank=True, help_text='Cheque number (if applicable)', max_length=50)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name (for cheque/transfer)', max_length=100)),
                ('payment_date', models.DateField(help_text='Date of payment')),
                ('cleared_date', models.DateField(blank=True, help_text='Date when payment was cleared (for cheques)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Payment notes or remarks')),
                ('customer', models.ForeignKey(help_text='Customer who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer')),
                ('installation_project', models.ForeignKey(blank=True, help_text='Related installation project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.installationproject')),
                ('invoice', models.ForeignKey(blank=True, help_text='Related invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.invoice')),
                ('payment_milestone', models.ForeignKey(blank=True, help_text='Related payment milestone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.paymentmilestone')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_milestone',
            field=models.ForeignKey(blank=True, help_text='Related payment milestone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='services.paymentmilestone'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_request',
            field=models.ForeignKey(blank=True, help_text='Related service request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='services.servicerequest'),
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('daily', 'Daily Summary'), ('weekly', 'Weekly Summary'), ('monthly', 'Monthly Summary'), ('quarterly', 'Quarterly Summary'), ('yearly', 'Yearly Summary')], help_text='Type of financial summary', max_length=20)),
                ('period_start', models.DateField(help_text='Start date of the summary period')),
                ('period_end', models.DateField(help_text='End date of the summary period')),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, help_text='Total amount invoiced in period', max_digits=15)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, help_text='Total amount collected in period', max_digits=15)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, help_text='Total outstanding amount', max_digits=15)),
                ('projects_invoiced', models.IntegerField(default=0, help_text='Number of projects invoiced')),
                ('projects_completed', models.IntegerField(default=0, help_text='Number of projects completed')),
                ('payments_received', models.IntegerField(default=0, help_text='Number of payments received')),
                ('average_payment_time', models.DecimalField(blank=True, decimal_places=2, help_text='Average payment time in days', max_digits=5, null=True)),
                ('overdue_invoices_count', models.IntegerField(default=0, help_text='Number of overdue invoices')),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total overdue amount', max_digits=15)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Summary',
                'verbose_name_plural': 'Financial Summaries',
                'db_table': 'financial_summaries',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['summary_type', 'period_end'], name='financial_s_summary_135fcd_idx'), models.Index(fields=['period_start', 'period_end'], name='financial_s_period__75ddb7_idx')],
                'unique_together': {('summary_type', 'period_start', 'period_end')},
            },
        ),
        migrations.AddIndex(
            model_name='paymentmilestone',
            index=models.Index(fields=['installation_project', 'status'], name='payment_mil_install_0e9314_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmilestone',
            index=models.Index(fields=['due_date'], name='payment_mil_due_dat_193ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmilestone',
            index=models.Index(fields=['status'], name='payment_mil_status_844544_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmilestone',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='valid_milestone_amount'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='payments_payment_c27a96_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'status'], name='payments_custome_04132e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='valid_payment_amount'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='invoices_custome_90a13d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_07776b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_due_dat_039a25_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoices_invoice_e14adb_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='valid_total_amount'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gte', models.F('invoice_date'))), name='valid_due_date'),
        ),
    ]
