# Generated by Django 4.2.7 on 2025-12-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], help_text='Type of action performed', max_length=50)),
                ('object_id', models.CharField(help_text='ID of the object that was modified', max_length=50)),
                ('model_name', models.CharField(help_text='Name of the model that was modified', max_length=50)),
                ('changes', models.JSONField(default=dict, help_text='Before and after values for changes')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the user')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('request_path', models.CharField(blank=True, help_text='URL path of the request', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method of the request', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('additional_data', models.JSONField(default=dict, help_text='Additional context data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Model name for which this retention policy applies', max_length=50, unique=True)),
                ('retention_days', models.IntegerField(choices=[(30, '30 days'), (90, '90 days'), (180, '6 months'), (365, '1 year'), (1095, '3 years'), (1825, '5 years'), (0, 'Never delete')], default=365, help_text='Number of days to retain audit logs (0 = never delete)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this retention policy is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Log Retention Policy',
                'verbose_name_plural': 'Audit Log Retention Policies',
                'db_table': 'audit_log_retention',
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveDataAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Model containing the sensitive data', max_length=50)),
                ('object_id', models.CharField(help_text='ID of the object accessed', max_length=50)),
                ('field_name', models.CharField(help_text='Name of the sensitive field accessed', max_length=50)),
                ('access_type', models.CharField(choices=[('VIEW', 'View'), ('EXPORT', 'Export'), ('PRINT', 'Print'), ('COPY', 'Copy')], help_text='Type of access', max_length=10)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the user')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('justification', models.TextField(blank=True, help_text='Business justification for accessing this data')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, help_text='When the data was accessed')),
            ],
            options={
                'verbose_name': 'Sensitive Data Access',
                'verbose_name_plural': 'Sensitive Data Access',
                'db_table': 'sensitive_data_access',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
