# Generated by Django 4.2.7 on 2025-12-31 10:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='Original data that was checked for duplicates')),
                ('potential_duplicates', models.JSONField(default=list, help_text='List of potential duplicate records found')),
                ('highest_confidence', models.FloatField(default=0.0, help_text='Highest confidence score among potential duplicates')),
                ('recommended_action', models.CharField(choices=[('create', 'Create New Record'), ('merge', 'Auto Merge'), ('review', 'Manual Review Required'), ('ignore', 'Ignore Duplicates')], help_text='Recommended action based on confidence scores', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_processed', 'Auto Processed')], default='pending', help_text='Current processing status', max_length=20)),
                ('final_action', models.CharField(blank=True, choices=[('create', 'Create New Record'), ('merge', 'Auto Merge'), ('review', 'Manual Review Required'), ('ignore', 'Ignore Duplicates')], help_text='Final action taken', max_length=20)),
                ('created_lead_id', models.IntegerField(blank=True, help_text='ID of lead created if action was create', null=True)),
                ('merged_into_id', models.IntegerField(blank=True, help_text='ID of record merged into if action was merge', null=True)),
                ('merged_into_type', models.CharField(blank=True, choices=[('lead', 'Lead'), ('customer', 'Customer')], help_text='Type of record merged into', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this was processed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the processing')),
            ],
            options={
                'verbose_name': 'Duplicate Detection Result',
                'verbose_name_plural': 'Duplicate Detection Results',
                'db_table': 'duplicate_detection_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the lead', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='Last name of the lead', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the lead', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='Phone number of the lead', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('converted', 'Converted'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new', help_text='Current status of the lead', max_length=20)),
                ('score', models.IntegerField(default=0, help_text='Lead score (0-100)')),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the lead', max_length=20)),
                ('interest_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', help_text='Interest level of the lead', max_length=20)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural')], default='residential', help_text='Type of property for solar installation', max_length=50)),
                ('estimated_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated solar capacity in kW', max_digits=10, null=True)),
                ('budget_range', models.CharField(choices=[('under_1_lakh', 'Under ₹1 Lakh'), ('1_to_3_lakh', '₹1-3 Lakh'), ('3_to_5_lakh', '₹3-5 Lakh'), ('5_to_10_lakh', '₹5-10 Lakh'), ('above_10_lakh', 'Above ₹10 Lakh'), ('not_specified', 'Not Specified')], default='not_specified', help_text='Budget range for solar installation', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Full address of the lead')),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State', max_length=100)),
                ('pincode', models.CharField(blank=True, help_text='PIN code', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_at', models.DateTimeField(blank=True, help_text='Date when lead was converted to customer', null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, help_text='Last time this lead was contacted', null=True)),
                ('original_data', models.JSONField(default=dict, help_text='Store original interaction data from frontend')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this lead')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('chatbot', 'Chatbot'), ('website', 'Website Visit'), ('form', 'Form Submission'), ('calculator', 'Solar Calculator'), ('other', 'Other')], help_text='Type of interaction', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject or title of the interaction', max_length=200)),
                ('description', models.TextField(help_text='Description of the interaction')),
                ('interaction_data', models.JSONField(default=dict, help_text='Additional data related to the interaction')),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the interaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Interaction',
                'verbose_name_plural': 'Lead Interactions',
                'db_table': 'lead_interactions',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the priority rule', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of the priority rule')),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Priority level assigned by this rule', max_length=20)),
                ('score_weight', models.IntegerField(default=10, help_text='Weight added to lead score when this rule matches')),
                ('conditions', models.JSONField(default=dict, help_text='Conditions that must be met for this rule to apply')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Priority Rule',
                'verbose_name_plural': 'Lead Priority Rules',
                'db_table': 'lead_priorities',
                'ordering': ['-score_weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Calculated score (0-100)')),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Assigned priority level', max_length=20)),
                ('scoring_factors', models.JSONField(default=dict, help_text='Breakdown of factors contributing to the score')),
                ('applied_rules', models.JSONField(default=list, help_text='List of priority rules that were applied')),
                ('reasoning', models.TextField(help_text='Human-readable explanation of the score')),
                ('calculator_data_used', models.BooleanField(default=False, help_text='Whether calculator data was used in scoring')),
                ('chatbot_data_used', models.BooleanField(default=False, help_text='Whether chatbot data was used in scoring')),
                ('interaction_data_used', models.BooleanField(default=False, help_text='Whether interaction history was used in scoring')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Score',
                'verbose_name_plural': 'Lead Scores',
                'db_table': 'lead_scores',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the lead source', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the lead source')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
                'db_table': 'lead_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManualReviewQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level for review', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('escalated', 'Escalated')], default='pending', help_text='Current review status', max_length=20)),
                ('review_started_at', models.DateTimeField(blank=True, help_text='When review was started', null=True)),
                ('review_completed_at', models.DateTimeField(blank=True, help_text='When review was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from the reviewer')),
            ],
            options={
                'verbose_name': 'Manual Review Queue Item',
                'verbose_name_plural': 'Manual Review Queue',
                'db_table': 'manual_review_queue',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MergeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_type', models.CharField(choices=[('lead_to_lead', 'Lead to Lead'), ('lead_to_customer', 'Lead to Customer'), ('customer_to_customer', 'Customer to Customer')], help_text='Type of merge operation', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', help_text='Status of merge operation', max_length=20)),
                ('source_record_type', models.CharField(choices=[('lead', 'Lead'), ('customer', 'Customer')], help_text='Type of source record', max_length=20)),
                ('source_record_id', models.IntegerField(help_text='ID of source record (will be merged/deleted)')),
                ('source_record_data', models.JSONField(help_text='Snapshot of source record data before merge')),
                ('target_record_type', models.CharField(choices=[('lead', 'Lead'), ('customer', 'Customer')], help_text='Type of target record', max_length=20)),
                ('target_record_id', models.IntegerField(help_text='ID of target record (will receive merged data)')),
                ('target_record_data_before', models.JSONField(help_text='Snapshot of target record data before merge')),
                ('target_record_data_after', models.JSONField(blank=True, help_text='Snapshot of target record data after merge', null=True)),
                ('confidence_score', models.FloatField(help_text='Confidence score that led to this merge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When merge operation started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When merge operation completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if merge failed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the merge')),
            ],
            options={
                'verbose_name': 'Merge Operation',
                'verbose_name_plural': 'Merge Operations',
                'db_table': 'merge_operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
