# Generated by Django 4.2.7 on 2025-12-25 19:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the lead source", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the lead source"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this source is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead Source",
                "verbose_name_plural": "Lead Sources",
                "db_table": "lead_sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name of the lead", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="Last name of the lead", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the lead",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Phone number of the lead",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("proposal_sent", "Proposal Sent"),
                            ("negotiation", "Negotiation"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                            ("on_hold", "On Hold"),
                        ],
                        default="new",
                        help_text="Current status of the lead",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(default=0, help_text="Lead score (0-100)"),
                ),
                (
                    "interest_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="medium",
                        help_text="Interest level of the lead",
                        max_length=20,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("agricultural", "Agricultural"),
                        ],
                        default="residential",
                        help_text="Type of property for solar installation",
                        max_length=50,
                    ),
                ),
                (
                    "estimated_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated solar capacity in kW",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_1_lakh", "Under ₹1 Lakh"),
                            ("1_to_3_lakh", "₹1-3 Lakh"),
                            ("3_to_5_lakh", "₹3-5 Lakh"),
                            ("5_to_10_lakh", "₹5-10 Lakh"),
                            ("above_10_lakh", "Above ₹10 Lakh"),
                            ("not_specified", "Not Specified"),
                        ],
                        default="not_specified",
                        help_text="Budget range for solar installation",
                        max_length=50,
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Full address of the lead"),
                ),
                (
                    "city",
                    models.CharField(blank=True, help_text="City", max_length=100),
                ),
                (
                    "state",
                    models.CharField(blank=True, help_text="State", max_length=100),
                ),
                (
                    "pincode",
                    models.CharField(blank=True, help_text="PIN code", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when lead was converted to customer",
                        null=True,
                    ),
                ),
                (
                    "last_contacted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this lead was contacted",
                        null=True,
                    ),
                ),
                (
                    "original_data",
                    models.JSONField(
                        default=dict,
                        help_text="Store original interaction data from frontend",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this lead"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to this lead",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Source of this lead",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leads.leadsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("chatbot", "Chatbot"),
                            ("website", "Website Visit"),
                            ("form", "Form Submission"),
                            ("calculator", "Solar Calculator"),
                            ("other", "Other"),
                        ],
                        help_text="Type of interaction",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject or title of the interaction",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the interaction"),
                ),
                (
                    "interaction_data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional data related to the interaction",
                    ),
                ),
                (
                    "interaction_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time of the interaction",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="Lead this interaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="leads.lead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded this interaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Interaction",
                "verbose_name_plural": "Lead Interactions",
                "db_table": "lead_interactions",
                "ordering": ["-interaction_date"],
                "indexes": [
                    models.Index(
                        fields=["lead", "interaction_date"],
                        name="lead_intera_lead_id_58c598_idx",
                    ),
                    models.Index(
                        fields=["interaction_type"],
                        name="lead_intera_interac_40e2bc_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="lead_intera_created_7ba86d_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="leads_email_554d9f_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["phone"], name="leads_phone_13acb4_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status"], name="leads_status_94f025_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["score"], name="leads_score_7739f8_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["created_at"], name="leads_created_e6e479_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["assigned_to"], name="leads_assigne_c5180e_idx"),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(
                condition=models.Q(score__gte=0, score__lte=100),
                name="valid_lead_score",
            ),
        ),
    ]
