# Generated by Django 6.0 on 2025-12-25 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        help_text="Original data that was checked for duplicates"
                    ),
                ),
                (
                    "potential_duplicates",
                    models.JSONField(
                        default=list,
                        help_text="List of potential duplicate records found",
                    ),
                ),
                (
                    "highest_confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Highest confidence score among potential duplicates",
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("create", "Create New Record"),
                            ("merge", "Auto Merge"),
                            ("review", "Manual Review Required"),
                            ("ignore", "Ignore Duplicates"),
                        ],
                        help_text="Recommended action based on confidence scores",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("auto_processed", "Auto Processed"),
                        ],
                        default="pending",
                        help_text="Current processing status",
                        max_length=20,
                    ),
                ),
                (
                    "final_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("create", "Create New Record"),
                            ("merge", "Auto Merge"),
                            ("review", "Manual Review Required"),
                            ("ignore", "Ignore Duplicates"),
                        ],
                        help_text="Final action taken",
                        max_length=20,
                    ),
                ),
                (
                    "created_lead_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of lead created if action was create",
                        null=True,
                    ),
                ),
                (
                    "merged_into_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of record merged into if action was merge",
                        null=True,
                    ),
                ),
                (
                    "merged_into_type",
                    models.CharField(
                        blank=True,
                        choices=[("lead", "Lead"), ("customer", "Customer")],
                        help_text="Type of record merged into",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this was processed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the processing"
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who processed this detection result",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Duplicate Detection Result",
                "verbose_name_plural": "Duplicate Detection Results",
                "db_table": "duplicate_detection_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ManualReviewQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level for review",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        help_text="Current review status",
                        max_length=20,
                    ),
                ),
                (
                    "review_started_at",
                    models.DateTimeField(
                        blank=True, help_text="When review was started", null=True
                    ),
                ),
                (
                    "review_completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When review was completed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewer_notes",
                    models.TextField(blank=True, help_text="Notes from the reviewer"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to review this item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "detection_result",
                    models.OneToOneField(
                        help_text="Associated duplicate detection result",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_queue_item",
                        to="leads.duplicatedetectionresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Review Queue Item",
                "verbose_name_plural": "Manual Review Queue",
                "db_table": "manual_review_queue",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MergeOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merge_type",
                    models.CharField(
                        choices=[
                            ("lead_to_lead", "Lead to Lead"),
                            ("lead_to_customer", "Lead to Customer"),
                            ("customer_to_customer", "Customer to Customer"),
                        ],
                        help_text="Type of merge operation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        help_text="Status of merge operation",
                        max_length=20,
                    ),
                ),
                (
                    "source_record_type",
                    models.CharField(
                        choices=[("lead", "Lead"), ("customer", "Customer")],
                        help_text="Type of source record",
                        max_length=20,
                    ),
                ),
                (
                    "source_record_id",
                    models.IntegerField(
                        help_text="ID of source record (will be merged/deleted)"
                    ),
                ),
                (
                    "source_record_data",
                    models.JSONField(
                        help_text="Snapshot of source record data before merge"
                    ),
                ),
                (
                    "target_record_type",
                    models.CharField(
                        choices=[("lead", "Lead"), ("customer", "Customer")],
                        help_text="Type of target record",
                        max_length=20,
                    ),
                ),
                (
                    "target_record_id",
                    models.IntegerField(
                        help_text="ID of target record (will receive merged data)"
                    ),
                ),
                (
                    "target_record_data_before",
                    models.JSONField(
                        help_text="Snapshot of target record data before merge"
                    ),
                ),
                (
                    "target_record_data_after",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of target record data after merge",
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Confidence score that led to this merge"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When merge operation started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When merge operation completed",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if merge failed"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the merge"
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the merge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merge Operation",
                "verbose_name_plural": "Merge Operations",
                "db_table": "merge_operations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="duplicatedetectionresult",
            index=models.Index(fields=["status"], name="duplicate_d_status_f32a36_idx"),
        ),
        migrations.AddIndex(
            model_name="duplicatedetectionresult",
            index=models.Index(
                fields=["recommended_action"], name="duplicate_d_recomme_92261a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="duplicatedetectionresult",
            index=models.Index(
                fields=["highest_confidence"], name="duplicate_d_highest_90e408_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="duplicatedetectionresult",
            index=models.Index(
                fields=["created_at"], name="duplicate_d_created_ab97ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manualreviewqueue",
            index=models.Index(fields=["status"], name="manual_revi_status_8273ba_idx"),
        ),
        migrations.AddIndex(
            model_name="manualreviewqueue",
            index=models.Index(
                fields=["priority"], name="manual_revi_priorit_561eed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manualreviewqueue",
            index=models.Index(
                fields=["assigned_to"], name="manual_revi_assigne_fe429c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manualreviewqueue",
            index=models.Index(
                fields=["created_at"], name="manual_revi_created_447a5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mergeoperation",
            index=models.Index(fields=["status"], name="merge_opera_status_2227f6_idx"),
        ),
        migrations.AddIndex(
            model_name="mergeoperation",
            index=models.Index(
                fields=["merge_type"], name="merge_opera_merge_t_f22fa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mergeoperation",
            index=models.Index(
                fields=["source_record_type", "source_record_id"],
                name="merge_opera_source__38094a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mergeoperation",
            index=models.Index(
                fields=["target_record_type", "target_record_id"],
                name="merge_opera_target__9f68c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mergeoperation",
            index=models.Index(
                fields=["created_at"], name="merge_opera_created_be9596_idx"
            ),
        ),
    ]
