# Generated by Django 4.2.7 on 2025-12-31 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeoperation',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the merge', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualreviewqueue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to review this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualreviewqueue',
            name='detection_result',
            field=models.OneToOneField(help_text='Associated duplicate detection result', on_delete=django.db.models.deletion.CASCADE, related_name='review_queue_item', to='leads.duplicatedetectionresult'),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='lead',
            field=models.ForeignKey(help_text='Lead this score belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='lead',
            field=models.ForeignKey(help_text='Lead this interaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who recorded this interaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(help_text='Source of this lead', on_delete=django.db.models.deletion.CASCADE, to='leads.leadsource'),
        ),
        migrations.AddField(
            model_name='duplicatedetectionresult',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed this detection result', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mergeoperation',
            index=models.Index(fields=['status'], name='merge_opera_status_2227f6_idx'),
        ),
        migrations.AddIndex(
            model_name='mergeoperation',
            index=models.Index(fields=['merge_type'], name='merge_opera_merge_t_f22fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='mergeoperation',
            index=models.Index(fields=['source_record_type', 'source_record_id'], name='merge_opera_source__38094a_idx'),
        ),
        migrations.AddIndex(
            model_name='mergeoperation',
            index=models.Index(fields=['target_record_type', 'target_record_id'], name='merge_opera_target__9f68c5_idx'),
        ),
        migrations.AddIndex(
            model_name='mergeoperation',
            index=models.Index(fields=['created_at'], name='merge_opera_created_be9596_idx'),
        ),
        migrations.AddIndex(
            model_name='manualreviewqueue',
            index=models.Index(fields=['status'], name='manual_revi_status_8273ba_idx'),
        ),
        migrations.AddIndex(
            model_name='manualreviewqueue',
            index=models.Index(fields=['priority'], name='manual_revi_priorit_561eed_idx'),
        ),
        migrations.AddIndex(
            model_name='manualreviewqueue',
            index=models.Index(fields=['assigned_to'], name='manual_revi_assigne_fe429c_idx'),
        ),
        migrations.AddIndex(
            model_name='manualreviewqueue',
            index=models.Index(fields=['created_at'], name='manual_revi_created_447a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='leadscore',
            index=models.Index(fields=['lead', 'calculated_at'], name='lead_scores_lead_id_7aa230_idx'),
        ),
        migrations.AddIndex(
            model_name='leadscore',
            index=models.Index(fields=['score'], name='lead_scores_score_e70d77_idx'),
        ),
        migrations.AddIndex(
            model_name='leadscore',
            index=models.Index(fields=['priority_level'], name='lead_scores_priorit_976769_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['lead', 'interaction_date'], name='lead_intera_lead_id_58c598_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['interaction_type'], name='lead_intera_interac_40e2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['created_at'], name='lead_intera_created_7ba86d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_email_554d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='leads_phone_13acb4_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_status_94f025_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['score'], name='leads_score_7739f8_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_created_e6e479_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='leads_assigne_c5180e_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0), ('score__lte', 100)), name='valid_lead_score'),
        ),
        migrations.AddIndex(
            model_name='duplicatedetectionresult',
            index=models.Index(fields=['status'], name='duplicate_d_status_f32a36_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicatedetectionresult',
            index=models.Index(fields=['recommended_action'], name='duplicate_d_recomme_92261a_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicatedetectionresult',
            index=models.Index(fields=['highest_confidence'], name='duplicate_d_highest_90e408_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicatedetectionresult',
            index=models.Index(fields=['created_at'], name='duplicate_d_created_ab97ff_idx'),
        ),
    ]
