# Generated by Django 6.0 on 2025-12-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_duplicatedetectionresult_manualreviewqueue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the priority rule",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the priority rule"),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        help_text="Priority level assigned by this rule",
                        max_length=20,
                    ),
                ),
                (
                    "score_weight",
                    models.IntegerField(
                        default=10,
                        help_text="Weight added to lead score when this rule matches",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Conditions that must be met for this rule to apply",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rule is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead Priority Rule",
                "verbose_name_plural": "Lead Priority Rules",
                "db_table": "lead_priorities",
                "ordering": ["-score_weight", "name"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="priority_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                help_text="Priority level of the lead",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeadScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(help_text="Calculated score (0-100)")),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        help_text="Assigned priority level",
                        max_length=20,
                    ),
                ),
                (
                    "scoring_factors",
                    models.JSONField(
                        default=dict,
                        help_text="Breakdown of factors contributing to the score",
                    ),
                ),
                (
                    "applied_rules",
                    models.JSONField(
                        default=list,
                        help_text="List of priority rules that were applied",
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(
                        help_text="Human-readable explanation of the score"
                    ),
                ),
                (
                    "calculator_data_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether calculator data was used in scoring",
                    ),
                ),
                (
                    "chatbot_data_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether chatbot data was used in scoring",
                    ),
                ),
                (
                    "interaction_data_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether interaction history was used in scoring",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="Lead this score belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_history",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Score",
                "verbose_name_plural": "Lead Scores",
                "db_table": "lead_scores",
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "calculated_at"],
                        name="lead_scores_lead_id_7aa230_idx",
                    ),
                    models.Index(fields=["score"], name="lead_scores_score_e70d77_idx"),
                    models.Index(
                        fields=["priority_level"], name="lead_scores_priorit_976769_idx"
                    ),
                ],
            },
        ),
    ]
