# Generated by Django 4.2.7 on 2025-12-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackgroundTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Name of the task function", max_length=100
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        help_text="Unique task identifier", max_length=50, unique=True
                    ),
                ),
                (
                    "args",
                    models.JSONField(
                        default=list, help_text="Task arguments as JSON list"
                    ),
                ),
                (
                    "kwargs",
                    models.JSONField(
                        default=dict, help_text="Task keyword arguments as JSON dict"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retry", "Retry"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Task result or error message", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                (
                    "retry_delay",
                    models.IntegerField(default=60, help_text="Retry delay in seconds"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5, help_text="Task priority (1=highest, 10=lowest)"
                    ),
                ),
            ],
            options={
                "db_table": "background_tasks",
                "ordering": ["priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority"],
                        name="background__status_8e7eba_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="background__created_6b2743_idx"
                    ),
                    models.Index(
                        fields=["task_name"], name="background__task_na_f87434_idx"
                    ),
                ],
            },
        ),
    ]
