# Generated by Django 4.2.7 on 2025-12-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Name of the task function', max_length=100)),
                ('task_id', models.CharField(help_text='Unique task identifier', max_length=50, unique=True)),
                ('args', models.JSONField(default=list, help_text='Task arguments as JSON list')),
                ('kwargs', models.JSONField(default=dict, help_text='Task keyword arguments as JSON dict')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, help_text='Task result or error message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay', models.IntegerField(default=60, help_text='Retry delay in seconds')),
                ('priority', models.IntegerField(default=5, help_text='Task priority (1=highest, 10=lowest)')),
            ],
            options={
                'db_table': 'background_tasks',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, help_text='User email if provided', max_length=254)),
                ('user_name', models.CharField(blank=True, help_text='User name if provided', max_length=200)),
                ('user_phone', models.CharField(blank=True, help_text='User phone if provided', max_length=20)),
                ('property_type', models.CharField(help_text='Type of property', max_length=50)),
                ('monthly_bill', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly electricity bill', max_digits=10, null=True)),
                ('roof_area', models.DecimalField(blank=True, decimal_places=2, help_text='Available roof area in sq ft', max_digits=10, null=True)),
                ('location', models.CharField(blank=True, help_text='Installation location', max_length=200)),
                ('estimated_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated system capacity in kW', max_digits=10, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated system cost', max_digits=12, null=True)),
                ('estimated_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated annual savings', max_digits=12, null=True)),
                ('payback_period', models.DecimalField(blank=True, decimal_places=1, help_text='Payback period in years', max_digits=5, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Raw calculator data')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', help_text='Processing status', max_length=20)),
                ('created_lead_id', models.IntegerField(blank=True, help_text='ID of created lead record', null=True)),
                ('processing_notes', models.TextField(blank=True, help_text='Processing notes')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('calculation_date', models.DateTimeField(help_text='When calculation was performed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When data was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calculator Data',
                'verbose_name_plural': 'Calculator Data',
                'db_table': 'calculator_data',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Chatbot session ID', max_length=100)),
                ('user_email', models.EmailField(blank=True, help_text='User email if provided', max_length=254)),
                ('user_name', models.CharField(blank=True, help_text='User name if provided', max_length=200)),
                ('user_phone', models.CharField(blank=True, help_text='User phone if provided', max_length=20)),
                ('conversation_data', models.JSONField(default=dict, help_text='Full conversation data from chatbot')),
                ('user_intent', models.CharField(blank=True, help_text='Detected user intent', max_length=100)),
                ('extracted_data', models.JSONField(default=dict, help_text='Extracted structured data from conversation')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', help_text='Processing status', max_length=20)),
                ('created_lead_id', models.IntegerField(blank=True, help_text='ID of created lead record', null=True)),
                ('processing_notes', models.TextField(blank=True, help_text='Processing notes')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('interaction_date', models.DateTimeField(help_text='When interaction occurred')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When interaction was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Interaction',
                'verbose_name_plural': 'Chatbot Interactions',
                'db_table': 'chatbot_interactions',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(help_text='Unique email ID from EmailJS', max_length=100, unique=True)),
                ('sender_email', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('sender_name', models.CharField(blank=True, help_text='Name of the sender', max_length=200)),
                ('subject', models.CharField(help_text='Email subject line', max_length=500)),
                ('raw_content', models.TextField(help_text='Raw email content as received')),
                ('parsed_data', models.JSONField(default=dict, help_text='Parsed data extracted from email')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('manual_review', 'Manual Review Required')], default='pending', help_text='Current processing status', max_length=20)),
                ('email_type', models.CharField(choices=[('lead_inquiry', 'Lead Inquiry'), ('service_request', 'Service Request'), ('quotation_request', 'Quotation Request'), ('general_inquiry', 'General Inquiry'), ('unknown', 'Unknown')], default='unknown', help_text='Detected email type', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Confidence score for email parsing (0.0 to 1.0)', max_digits=3)),
                ('created_lead_id', models.IntegerField(blank=True, help_text='ID of created lead record', null=True)),
                ('created_service_request_id', models.IntegerField(blank=True, help_text='ID of created service request', null=True)),
                ('processing_notes', models.TextField(blank=True, help_text='Notes from processing')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('received_at', models.DateTimeField(help_text='When email was received')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When email was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-received_at'],
            },
        ),
    ]
