# Generated by Django 4.2.7 on 2025-12-31 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed this email (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatbotinteraction',
            index=models.Index(fields=['session_id'], name='chatbot_int_session_0c36a0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotinteraction',
            index=models.Index(fields=['user_email'], name='chatbot_int_user_em_7a6ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotinteraction',
            index=models.Index(fields=['processing_status'], name='chatbot_int_process_e12d68_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotinteraction',
            index=models.Index(fields=['interaction_date'], name='chatbot_int_interac_dd5688_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatordata',
            index=models.Index(fields=['user_email'], name='calculator__user_em_1aa0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatordata',
            index=models.Index(fields=['processing_status'], name='calculator__process_7ff104_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatordata',
            index=models.Index(fields=['calculation_date'], name='calculator__calcula_d211f1_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['status', 'priority'], name='background__status_8e7eba_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['created_at'], name='background__created_6b2743_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['task_name'], name='background__task_na_f87434_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_id'], name='email_logs_email_i_2b5752_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['sender_email'], name='email_logs_sender__3cc99b_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['processing_status'], name='email_logs_process_0a20ab_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_type'], name='email_logs_email_t_fe5930_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['received_at'], name='email_logs_receive_b9eed4_idx'),
        ),
    ]
