# Generated by Django 4.2.7 on 2025-12-31 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(help_text='Unique error identifier', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('email_processing', 'Email Processing'), ('api_integration', 'API Integration'), ('database', 'Database'), ('external_service', 'External Service'), ('validation', 'Validation'), ('authentication', 'Authentication'), ('permission', 'Permission'), ('system', 'System')], help_text='Error category', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Error severity level', max_length=20)),
                ('error_type', models.CharField(help_text='Type of error (exception class name)', max_length=200)),
                ('error_message', models.TextField(help_text='Error message')),
                ('traceback', models.TextField(help_text='Full error traceback')),
                ('context', models.JSONField(default=dict, help_text='Additional context information')),
                ('user_id', models.IntegerField(blank=True, help_text='ID of user associated with error', null=True)),
                ('request_data', models.JSONField(default=dict, help_text='Request data that caused the error')),
                ('recovery_attempted', models.BooleanField(default=False, help_text='Whether recovery was attempted')),
                ('recovery_successful', models.BooleanField(default=False, help_text='Whether recovery was successful')),
                ('recovery_notes', models.TextField(blank=True, help_text='Notes about recovery attempt')),
                ('resolved', models.BooleanField(default=False, help_text='Whether error has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When error was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about error resolution')),
                ('timestamp', models.DateTimeField(help_text='When error occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the error', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'db_table': 'error_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['error_id'], name='error_logs_error_i_d49a9e_idx'), models.Index(fields=['category'], name='error_logs_categor_59a365_idx'), models.Index(fields=['severity'], name='error_logs_severit_798c67_idx'), models.Index(fields=['timestamp'], name='error_logs_timesta_673a33_idx'), models.Index(fields=['resolved'], name='error_logs_resolve_5e3026_idx')],
            },
        ),
    ]
