# Generated by Django 4.2.7 on 2025-12-25 19:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name of the customer", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name of the customer",
                        max_length=100,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the customer",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Phone number of the customer",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Company name (for commercial customers)",
                        max_length=200,
                    ),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True,
                        help_text="GST number for business customers",
                        max_length=15,
                    ),
                ),
                ("address", models.TextField(help_text="Full address of the customer")),
                ("city", models.CharField(help_text="City", max_length=100)),
                ("state", models.CharField(help_text="State", max_length=100)),
                ("pincode", models.CharField(help_text="PIN code", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("churned", "Churned"),
                        ],
                        default="active",
                        help_text="Current status of the customer",
                        max_length=20,
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("agricultural", "Agricultural"),
                        ],
                        default="residential",
                        help_text="Type of customer",
                        max_length=20,
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total value of all projects/contracts",
                        max_digits=12,
                    ),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Outstanding amount to be paid",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this customer"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to manage this customer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        blank=True,
                        help_text="Original lead if this customer was converted from a lead",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("contact_update", "Contact Update"),
                            ("financial_update", "Financial Update"),
                            ("interaction", "Interaction"),
                            ("project_update", "Project Update"),
                            ("service_request", "Service Request"),
                            ("other", "Other"),
                        ],
                        help_text="Type of history entry",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or summary of the history entry",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of what happened"),
                ),
                (
                    "old_values",
                    models.JSONField(
                        default=dict, help_text="Previous values (for change tracking)"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        default=dict, help_text="New values (for change tracking)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer this history entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="customers.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made this change or interaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer History",
                "verbose_name_plural": "Customer History",
                "db_table": "customer_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "created_at"],
                        name="customer_hi_custome_dc4147_idx",
                    ),
                    models.Index(
                        fields=["history_type"], name="customer_hi_history_606c63_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="customer_hi_created_6edfda_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customers_email_92e882_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="customers_phone_91048b_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["status"], name="customers_status_47bd31_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_type"], name="customers_custome_3f7c53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["created_at"], name="customers_created_c63477_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["assigned_to"], name="customers_assigne_e7f573_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(total_value__gte=0), name="valid_total_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(outstanding_amount__gte=0),
                name="valid_outstanding_amount",
            ),
        ),
    ]
