# Generated by Django 4.2.7 on 2025-12-31 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made this change or interaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to manage this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead',
            field=models.OneToOneField(blank=True, help_text='Original lead if this customer was converted from a lead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='customerhistory',
            index=models.Index(fields=['customer', 'created_at'], name='customer_hi_custome_dc4147_idx'),
        ),
        migrations.AddIndex(
            model_name='customerhistory',
            index=models.Index(fields=['history_type'], name='customer_hi_history_606c63_idx'),
        ),
        migrations.AddIndex(
            model_name='customerhistory',
            index=models.Index(fields=['created_at'], name='customer_hi_created_6edfda_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_email_92e882_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_phone_91048b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='customers_status_47bd31_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='customers_custome_3f7c53_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='customers_created_c63477_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['assigned_to'], name='customers_assigne_e7f573_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('total_value__gte', 0)), name='valid_total_value'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('outstanding_amount__gte', 0)), name='valid_outstanding_amount'),
        ),
    ]
